### ISSUE TITLE
getsubscription returns plan and not subscription (TS)

### ISSUE THREAD

**Issue by HiroForYou** [giwiro/culqi-node#29]
![image](https://github.com/giwiro/culqi-node/assets/40742491/9b18d190-ffec-4cbc-b68d-76b3ce60bb42)

![image](https://github.com/giwiro/culqi-node/assets/40742491/eede224a-8921-4b53-85b9-0c2ceadf98a7)

why does the subscriptions object return plans instead of a subscription? It's strange, when I do a getsubscription it should return a subscription and not a plan

**Comment by HiroForYou** [comment]
the source code must be corrected, changing the imports. I temporarily corrected it like this
![image](https://github.com/giwiro/culqi-node/assets/40742491/3dcc231d-4e9b-417d-9b5f-8b5a161aa097)

**Comment by giwiro** [comment]
All issues must be written in english pls.

**Comment by giwiro** [comment]
Thanks for the heads up, it was just a typing problem. It was fixed in the commit 4d28fffc5d8d59b71a06b4a5d7524b0f4269c148 in the branch dev. I will be pushing a new version with this fix along some deps update.

**Comment by giwiro** [comment]
It's not done yet tho. I'm waiting for the change of dev tooling. I will close this after that. It will take me like this weekend to get this done.

**Comment by giwiro** [comment]
I just pushed a new version [v2.1.0](https://www.npmjs.com/package/culqi-node/v/2.1.0).
