### ISSUE TITLE
Clientes

### ISSUE THREAD

**Issue by mmo-uy** [giwiro/culqi-node#9]
Hi @giwiro nice work congrats. 
Is there any plans to implement "clientes" web service wrapper?
Greetings

Hola @giwiro buen trabajo. Felicitaciones.
¿Hay planes para implementar un wrapper para el servicio de "clientes"?
Saludos

**Comment by giwiro** [comment]
Hi, what do you mean by "clientes" ?
Perhaps this: [clientes](https://apidocs.culqi.com/#/clientes) ?
If so, then it is already implemented in this file: https://github.com/giwiro/culqi-node/blob/master/src/customers.ts
You can check the test file in case you want to know how to implement it exactly: https://github.com/giwiro/culqi-node/blob/master/tests/customers.test.ts

Here is an snippet of how to use it:

```javascript
import {customers} from '../src/customers';
const resp = await customers.createCustomer({
    first_name: 'Richard',
    last_name: 'Hendricks',
    email: uniqueEmail,
    address: 'San Francisco Bay Area',
    address_city: 'Palo Alto',
    country_code: 'US',
    phone_number: '6505434800',
});
```
